name: Deploy WordPress Theme to Loopia

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload to Loopia via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftpcluster.loopia.se
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /dotbee.se/public_html/wp-content/themes/dotbee/
